// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package api

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCeb639cdDecodeGithubComAndrdruGoTemplateInternalApi(in *jlexer.Lexer, out *UserAuthorizeReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email":
			out.Email = string(in.String())
		case "pass":
			out.Pass = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCeb639cdEncodeGithubComAndrdruGoTemplateInternalApi(out *jwriter.Writer, in UserAuthorizeReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"pass\":"
		out.RawString(prefix)
		out.String(string(in.Pass))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserAuthorizeReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCeb639cdEncodeGithubComAndrdruGoTemplateInternalApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserAuthorizeReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCeb639cdEncodeGithubComAndrdruGoTemplateInternalApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserAuthorizeReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCeb639cdDecodeGithubComAndrdruGoTemplateInternalApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserAuthorizeReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCeb639cdDecodeGithubComAndrdruGoTemplateInternalApi(l, v)
}
