scrape_configs:
  - job_name: 'scraper'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          job: "local-scraper"
          instance: "host1:8080"
